### ISSUE TITLE
Experimental environment and data processing

### ISSUE THREAD

**Issue by lzh-pro666** [wangjs9/Muffin#1]
Hello, your job is very meaningful. I want to reproduce this article. Can you provide more information about the env.yml file, the format of the two dataset files in data processing, and the data_decess.by file? thank you very much!!

**Comment by wangjs9** [comment]
Thank you for your interest! I apologize for any confusion, and I will update the README as soon as possible. There is no specific env.yml or data processing file. For training each base model and muffin model, you can use the environment and data processing associated with the base model. In fact, I use the ESConv environment for nearly all model training.

Best Regards
